FROM node:20.14.0-alpine3.20 AS base

# install dependencies
FROM base AS deps

WORKDIR /app

COPY package.json .
COPY yarn.lock .

RUN yarn --frozen-lockfile

# build
FROM base AS builder

WORKDIR /app

COPY --from=deps app/node_modules node_modules
COPY . .

RUN yarn build

# export
FROM nginx:1.27-alpine AS runner

COPY --from=builder /app/out /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
