name: Deploy Staging Native [NextJs Standalone]

on:
  push:
    branches:
    - ci

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - uses: actions/cache@v4
      with:
        path: ${{ github.workspace }}/.next/cache
        key: ${{ runner.os }}-nextjs-${{ hashFiles('**/yarn.lock') }}-${{ hashFiles('**/*.js', '**/*.jsx', '**/*.ts', '**/*.tsx') }}
        restore-keys: ${{ runner.os }}-nextjs-${{ hashFiles('**/yarn.lock') }}

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20
        # cache: 'yarn'
        # cache-dependency-path: '**/yarn.lock'

    - name: Install dependencies
      run: yarn --frozen-lockfile
    
    - name: Build
      run: yarn build
    
    - name: Deploy
      run: |
        mkdir -p $HOME/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > "$HOME/.ssh/${{ github.sha }}"
        chmod 600 "$HOME/.ssh/${{ github.sha }}"

        ls -la .
        ls -la .next/standalone


        rsync -azh --delete -e "ssh -i $HOME/.ssh/${{ github.sha }} -o StrictHostKeyChecking=no" \
        public ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }}:/app/nextjs
        
        rsync -azh --delete -e "ssh -i $HOME/.ssh/${{ github.sha }} -o StrictHostKeyChecking=no" \
        .next/standalone/* ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }}:/app/nextjs

        rsync -azh --delete -e "ssh -i $HOME/.ssh/${{ github.sha }} -o StrictHostKeyChecking=no" \
        .next/standalone/.next ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }}:/app/nextjs

        rsync -azh --delete -e "ssh -i $HOME/.ssh/${{ github.sha }} -o StrictHostKeyChecking=no" \
        .next/static ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }}:/app/nextjs/.next

        ssh -i $HOME/.ssh/${{ github.sha }} -o StrictHostKeyChecking=no ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }} << EOF
        chown -R alpha:alpha /app/nextjs
        sudo systemctl restart nextjs
        EOF
    
    - name: Notify
      run: |
        curl -XPOST -H 'Content-type: application/json' \
        https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage \
        --data '{
          "chat_id": "${{ secrets.TELEGRAM_CHAT_ID }}",
          "parse_mode": "MarkdownV2",
          "text": "🚀 *Deployed*
          👉 Workflow: ${{ github.workflow }}
          👉 Actions: [Here](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})
          📄 Repository: [Here](https://github.com/${{ github.repository }})
          📄 See changes: [Here](https://github.com/${{ github.repository }}/commit/${{github.sha}})
          "
        }'